- trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.lambda_telegram
    data:
      message: "home assistant start"
  alias: hass_start

- trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: notify.lambda_telegram
    data: 
      message: "home assistant shutdown"
  alias: hass_shutdown

#- trigger:
#    platform: state
#    entity_id: sensor.rfbridge0
#  action:
#    service: notify.lambda_telegram
#    data:
#      message: "rf bridge triggered, key: {{ states.sensor.rfbridge0.state }}, last_changed: {{ states.sensor.rfbridge0.last_changed }}"

- alias: Turn on closet light when there is movement
  trigger:
    platform: state
    entity_id: sensor.rfbridge0
  condition:
    - condition: template
      value_template: "{{ states.sensor.rfbridge0.state == '1' or states.sensor.rfbridge0.state == '2' }}"
  action:
    - service: mqtt.publish
      data:
        topic: hass/sensors/pir/closet
        payload_template: '{{ as_timestamp(states.sensor.rfbridge0.last_changed) }}'
    - service: mqtt.publish
      data:
        topic: hass/switches/virtual/closet
        payload: '1'
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/basic-1/POWER
        payload: 'ON'


- alias: Turn of lights by time
  trigger:
    platform: time
    seconds: 30
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now()) - (states.sensor.pircloset.state | float)) > 30 and states.sensor.virtualswitch.state == '1' }}"
  action:
    - service: mqtt.publish
      data:
        topic: hass/switches/virtual/closet
        payload: '0'
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/basic-1/POWER
        payload: 'OFF'
