- trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.lambda_telegram
    data:
      message: "home assistant start"
  alias: hass_start

- trigger:
    platform: homeassistant
    event: shutdown
  action:
    service: notify.lambda_telegram
    data: 
      message: "home assistant shutdown"
  alias: hass_shutdown

- alias: включить зеркало по движению
  trigger:
    platform: state
    entity_id: sensor.rfbridge0
  condition:
    - condition: template
      value_template: "{{ states.sensor.rfbridge0.state == 'D2FA5E'}}"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.mirror

- alias: rf bridge debug
  trigger:
    platform: state
    entity_id: sensor.rfbridge0
  action:
    service: notify.filelogger
    data:
      message: "rf bridge triggered, data: {{ states.sensor.rfbridge0.state }}"

- alias: Turn on closet light by button
  trigger:
    platform: state
    entity_id: input_boolean.closet_light
  action:
    - service: mqtt.publish
      data:
        topic: hass/sensors/pir/closet
        payload_template: '{{ as_timestamp(now()) }}'
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/basic-1/POWER
        payload_template: '{{ states.input_boolean.closet_light.state.upper() }}'

- alias: Turn on closet light when there is movement
  trigger:
    platform: state
    entity_id: sensor.rfbridge0
  condition:
    - condition: template
      value_template: "{{ (states.sensor.rfbridge0.state == '393F91' or states.sensor.rfbridge0.state == 'D68A9E') }}"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.closet_light

- alias: Turn off closet lights by time
  trigger:
    platform: time
    seconds: 5
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now()) - (states.sensor.pircloset.state | float)) > (states.input_select.closet_timeout.state | float) and states.binary_sensor.basic1.state == 'on' }}"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.closet_light

- alias: Выключить зеркало по времени
  trigger:
    platform: time
    seconds: 5
  condition:
    - condition: template
      value_template: "{{ (as_timestamp(now()) - (states.sensor.pirmirror.state | float)) > (states.input_number.mirror_duration.state | float) and states.binary_sensor.nodemcu0.state == 'on' }}"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.mirror


#- alias: Turn off plants light by time
#  trigger:
#    platform: time
#    at: '22:15:00'
#  action:
#    service: homeassistant.turn_off
#    entity_id: input_boolean.plants_light

#- alias: Turn on plants light
#  trigger:
#    platform: time
#    at: '18:00:00'
#  action:
#    service: homeassistant.turn_on
#    entity_id: input_boolean.plants_light

- alias: Включить лампу для цветов по времени
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.plants_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.plants_light

- alias: Выключить лампу для цветов по времени
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.plants_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.plants_light

- alias: Turn on plants light by button
  trigger:
    platform: state
    entity_id: input_boolean.plants_light
  action:
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/basic-2/POWER
        payload_template: '{{ states.input_boolean.plants_light.state.upper() }}'

- alias: Включить зеркало
  trigger:
    platform: state
    entity_id: input_boolean.mirror
  action:
    - service: mqtt.publish
      data:
        topic: hass/sensors/pir/mirror
        payload_template: '{{ as_timestamp(now()) }}'
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/nodemcu-0/POWER
        payload_template: "{{ states.input_boolean.mirror.state.upper() }}"

- alias: Установить текущую яркость зеркала
  trigger:
    platform: state
    entity_id: input_number.mirror_current_brightness
  action:
    - service: mqtt.publish
      data:
        topic: shouse/cmnd/nodemcu-0/BRIGHTNESS
        payload_template: "{{ states.input_number.mirror_current_brightness.state | int }}"


