- platform: mqtt
  name: "basic-0"
  state_topic: "shouse/cmnd/basic-0/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  force_update: true

- platform: mqtt
  name: "basic-1"
  state_topic: "shouse/cmnd/basic-1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  force_update: true

- platform: mqtt
  name: "basic-2"
  state_topic: "shouse/cmnd/basic-2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  force_update: true
