#- platform: mqtt
#  name: "Closet Motion Sensor"
#  state_topic: "shouse/tele/rfbridge-0/RESULT"
#  device_class: motion

#- platform: mqtt
#  name: "rf remote A"
#  state_topic: "shouse/tele/rfbridge-0/RESULT"
#  payload_on: "3"
#  payload_off: "0"
#  device_class: opening
#  value_template: '{{ value_json.RfReceived.RfKey }}'

- platform: mqtt
  name: "closet-sensors"
  state_topic: "hass/options/sensors/closet"
  payload_on: "1"
  payload_off: "0"
  force_update: true
