- platform: yr

- platform: mqtt
  name: "rf-bridge-0"
  state_topic: "shouse/tele/rfbridge-0/RESULT"
  value_template: '{{ value_json.RfReceived.Data }}'
  force_update: true

- platform: mqtt
  name: "pir-closet"
  state_topic: "hass/sensors/pir/closet"
  force_update: true

- platform: mqtt
  name: "pir-mirror"
  state_topic: "hass/sensors/pir/mirror"
  force_update: true

- platform: mqtt
  name: "basic-0"
  state_topic: "shouse/cmnd/basic-0/POWER"

- platform: time_date
  name: "time"
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
